# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: vcenter.local
  become: yes

  tasks:

- name: Call Roles
  hosts: vcenter.local
  roles:
   #- hostname
   - firewalld
   #- ntp-config
   - motd
